# Generated by Django 5.2.6 on 2025-09-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ifh',
        ),
    ]
