# Generated by Django 3.2.23 on 2024-01-26 12:46

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('recomsys', '0002_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
