# Generated by Django 3.2.23 on 2024-01-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomsys', '0003_recommend_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
