# Generated by Django 3.2.23 on 2024-01-26 13:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recomsys', '0005_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='item',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='recommend',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommend',
            name='search_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
